const Routes = {
    LOGIN: 'LOGIN',
    NOTIFICATION_SETTING: 'NOTIFICATION_SETTING',
    ABOUT_ME: 'ABOUT_ME',
    TEST: 'TEST',
    PAYMENT: 'PAYMENT',
    LOGIN_VERIFY: 'LOGIN_VERIFY',
    HELP_CENTER: 'HELP_CENTER',
    PRIVACY_POLICY: 'PRIVACY_POLICY',
    TERMS: 'TERMS',
    ERROR_SCREEN: 'ERROR_SCREEN',
};

export {Routes};
